### ISSUE TITLE
plotdim (and/or other basic descriptors) as attributes?

### ISSUE THREAD

**Issue by gabrielareto** [forestgeo/fgeo.abundance#30]
There could be very basic function reading x, y coordinates on the raw data to estimate the plot dimensions, to append that as an attribute that could be inherited later on.

The same applies to an attribute called "siteID" or something like that, identifying the site. Some table storing basic info about those sites, including plotdim, could be maintained as data within the package.

**Comment by maurolepore** [comment]
The issue with attributes is that they are easily lost during data transformations -- even small ones ([e.g.](https://github.com/forestgeo/fgeo.abundance/issues/43#issuecomment-392155383)).

See also:
`fgeo.habitat::extract_gridsize()`
`fgeo.habitat::extract_gridsize()`
`guess_plotdim()`
`guess_max()`
