### ISSUE TITLE
Why do we need (dbh) units?

### ISSUE THREAD

**Issue by gabrielareto** [forestgeo/fgeo.abundance#42]
I had a look to the abundance functions your are working on. I think that "validate dbh unit" function, and similars, are very useful. Very informative function names.

Some thoughts about dbh units:

- we don't need units at all. If the dbh is expressed in cm, the basal area would be expressed in cm^2 and the biomass in grams (if wood density is expressed in grams/cm^3). In general, I think units transformation within code or formulas is a risky move. How difficult/easy would be to just get rid of this?

- for the complete dataset dbh units can be calculated fairly robustly even in the presence of errors, missing values, etc. If the dbh is on cm, a very low quantile of dbh's should be >10, and there must be few things above 50 and (almost) none above 5000. We know how real forests look like, we can take advantage of that. However, this estimate won't work if one has filtered the data to include just canopy trees, for example, or certain species only.

- because of the previous limitation, we may think about the inheritance of "dbh_units" as an attribute.

**Comment by maurolepore** [comment]
Relates to #43. Agree that whenever possible we need not to specify dbh units.

**Comment by maurolepore** [comment]
For all things 'unit' see the __units__ package: https://cran.r-project.org/web/packages/units/vignettes/units.html#setting-units-unit-conversion

**Comment by maurolepore** [comment]
See `fgeo.tool::convert_units()`.
