### ISSUE TITLE
multi-dimensional arrays after splitting data

### ISSUE THREAD

**Issue by gabrielareto** [forestgeo/fgeo.abundance#45]
during the meeting with @seanmcm and Stuart we discussed the possibility of splitting data into arrays in multiple ways, and these arrays could be the input for many other functions.

the splitting function needs to attach the splitting criteria to the resulting array somehow. Otherwise, it will be difficult to know what the array contains.

btw, the rowSums and colSums functions have the dims argument to make sums in any direction in a vectorized way. That could be potentially quite useful.

**Comment by maurolepore** [comment]
Closing until I find the need to input arrays.
